# Generated by Django 4.2.1 on 2023-05-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_prof_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prof_pic',
        ),
    ]
