# Generated by Django 4.2.1 on 2023-05-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_bio_alter_book_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_read',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
